### ISSUE TITLE
`ParseError: Unexpected end of input` no matter what 😭

### ISSUE THREAD

**Issue by roc** [epeli/node-hbsfy#45] opened 2015-06-24 21:31 UTC
It straight up seems not to be working for me, as though I'd failed to add the transform to my command.

`browserify -t hbsfy app/init.js > app/build.js` 

yields:
`ParseError: Unexpected end of input`

which is the same result as running 

`browserify app/init.js > app/build.js` 

```shell
template.hbs:2
<h2>I am dying</h2>
      ^
ParseError: Unexpected identifier
```

### template.hbs

```html
<h1>Help me</h1>
<h2>I am dying</h2>
````

### view.js

```javascript
var Marionette  = require('backbone.marionette');
var template   = require('app/templates/template.hbs');

module.exports = Marionette.ItemView.extend({
    template: template
});
```

### dependencies

```json
"devDependencies": {
    "backbone": "^1.2.1",
    "backbone.marionette": "^2.4.2",
    "browserify": "^10.2.4",
    "handlebars": "^3.0.0",
    "hbsfy": "~2.2.1",
    "jquery": "^2.1.4",
    "underscore": "^1.8.3",
    "watch": "^0.16.0"
},
```

I'm a lost noob and I can't figure out what on earth is missing. I've tried  `npm install handlebars@1` and `@2` with no sucess...

**Comment by kirbysayshi** [comment] 2015-10-11 02:32
I'm not sure what the problem is, but there are a few things to try.

First: I see you're requiring the template via `require('app/templates/template.hbs')`. Since the template is not within a dependency, you should use a relative path: `var template = require('./app/templates/template.hbs')`. I don't think this is the actual problem, but just to be sure.

Second, are you on Windows? What editor are you using? Sometimes certain editors stick hidden characters into files, especially on Windows.

If you're still having troubles, could you make a gist with the files that are demonstrating the problem? I'm hesitant to copy/paste the examples you gave simply because the problem is likely specific to your exact files or platform.

**Comment by kirbysayshi** [comment] 2016-01-25 06:25
@roc if you decide to come back to this, please reopen the issue! In the meantime, I'm going to close it.

**Closed by kirbysayshi** 2016-01-25 06:25 UTC
